### PR TITLE
Issue2 installer - windows batch

### PR DESCRIPTION
**Pull request by ngriff43**
This is a pull request for the windows installer batch file

### CODE REVIEW

**Comment by JayD3254** [comment]
Everything in the installer looks good.

**Comment by MackPacker7** [comment]
Yep, looks good!

**Review by JayD3254 — COMMENTED** [review]
More comments would be good to add to explain the script better. Other than that, everything looks good.

**Review by MackPacker7 — COMMENTED** [review]
Looks good, pretty self-explanatory. Maybe see if you can wrap it up and install anaconda with it using an installer or something.

**Pull request merged**
